name: My workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build the site
      run: bundle exec jekyll build
    - name: Test only - ls the files
      run: ls -lh ./_site/wp-content/uploads
    - name: Test only - reduce the total upload size to fit within the GoStatic limit
      run: rm -rf ./_site/wp-content/uploads/201*
    - name: Test only - ls the files again
      run: ls -lh ./_site/wp-content/uploads
    - name: Deploy via GoStatic
      id: deploy
      uses: DigitalSVN/GoStatic@v1.0
      with:
        api-token: ${{ secrets.GOSTATIC_API_TOKEN }}
        source-dir: './_site'
    - name: Output the deployment URL
      run: echo "URL ${{ steps.deploy.outputs.url }}"
    - name: Output the deployment URL in a comment on the pull request
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'URL ready:  ${{ steps.deploy.outputs.url }}' });
